### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by heygrady** [FontCustom/fontcustom#17]
Windows has Font Forge Support but it isn't immediately obvious how to make FontForge support available to Python so that FontCustom will work seamlessly cross-platform. I realize that this could be seen as a FontForge issue, not a FontCustom issue, but a workaround is likely possible.

http://www.mpetroff.net/software/fontforge-windows/

**Comment by skolmer** [comment]
I got fontcustom running on Windows 8 x64. I had to make some small windows specific changes to the fontcustom source code. Most issues were related to external libraries like FontForge.

Here is a simple how-to:

***fontcustom on Windows 8 x64***

1. Install phyton (*Let the installer append the Python Path to the %PATH% variable!*) python-2.7.9.amd64.msi from https://www.python.org/downloads/release/python-279/

2. Install Ruby 1.9.3-p545 (*Let the installer append the Ruby Path to the %PATH% variable*) from http://rubyinstaller.org/downloads/archives

3. Log-off and Log-on to allow the installer to update your %PATH% variable

4. Make sure you have a RubyGems version (gem --version) <= 2.3.0 or downgrade with "gem update --system 2.3.0";

5. Download "FontForge-mingw-w64-i686-6bfa9e-r2.7z" from http://fontforgebuilds.sourceforge.net/

6. Extract FontForge to to "C:\Program Files\FontForge"

7. Download "sfnt2woff.exe" from https://people.mozilla.org/~jkew/woff/

8. Copy "sfnt2woff.exe" to "C:\Program Files\FontForge"

9. Append ";C:\Program Files\FontForge" to the PATH Environment Variable

10. Close all cmd Windows!

11. Download the Ruby Development Kit (DevKit-tdm-32-4.5.2-20111229-1559-sfx) from 
http://rubyinstaller.org/downloads/

12. Extract the DevKit to [Ruby_Dir]\devkit

13. Open cmd and cd to [Ruby_Dir]\devkit, run "ruby dk.rb init" and "ruby dk.rb install" 

14. Open cmd and run "gem install fontcustom" (If you get the Error "Makefile:165: *** target pattern contains no `%'.  Stop." go back to step 4)

15. Open "[Ruby_Dir]\lib\ruby\gems\1.9.1\gems\fontcustom-1.3.7\lib\fontcustom\base.rb" in a texteditor and remove lines 33-36:
```
      # fontforge = `which fontforge`
      # if fontforge == "" || fontforge == "fontforge not found"
      #   raise Fontcustom::Error, "Please install fontforge first. Visit <http://fontcustom.com> for instructions."
      # end 
```

16. Open "[Ruby_Dir]\lib\ruby\gems\1.9.1\gems\fontcustom-1.3.7\lib\fontcustom\scripts\generate.py" in a texteditor and change line 121:
```
	subprocess.call('mv ' + fontfile + '.eotlite ' + fontfile + '.eot', shell=True)
```
TO:
```
	subprocess.call(str('move ' + fontfile + '.eotlite ' + fontfile + '.eot').replace(u'/',u'\\'), shell=True)
```

17: Open cmd and cd to you project directory.

18. Run "fontcustom compile YOUR_ICON_DIR_INSIDE_THE_PROJ_DIR"

**Comment by TWiStErRob** [comment]
@skolmer's hacky steps can be replaced with making shims for those commands. Don't forget to make them available on PATH somewhere.

Instead of editing `base.rb` make a file named `which.bat` (based on [`where.exe`](http://stackoverflow.com/a/304447/253468)):
```batch
where %*
```

Instead of editing `generate.py` make file named `mv.bat` (based on `move` builtin in `cmd.exe`):
```batch
@echo off
setlocal enabledelayedexpansion
set args=
for %%x in (%*) do (set "arg=%%~x" && set args=!args! "!arg:/=\!")
move %args% >NUL
endlocal
```

**Comment by TWiStErRob** [comment]
@kaizau it would take so few steps on your part to enable seamless Windows integration. Please change your shell calls to platform independent calls and we're good to go.

 1. Wrap `which fontforge` in `if !Gem.win_platform?` or use `where` (equiv of `which` in Windows)  
or better yet [“which in ruby”: Checking if program exists in $PATH from ruby](http://stackoverflow.com/q/2108727/253468)
 2. `subprocess.call('mv ' + ..., shell=True)`  -> [Moving a file in python](http://stackoverflow.com/q/8858008/253468)
 3. If you're real nice you include the [sfnt2woff.exe](https://people.mozilla.org/~jkew/woff/sfnt2woff.exe) the same way you did with the [Unix executable](https://github.com/FontCustom/fontcustom/blob/master/lib/fontcustom/scripts/sfnt2woff).

You could copy @skolmer's genius play-by-play to your readme as well.

**Comment by skolmer** [comment]
@TWiStErRob thanks for these great suggestions! If you find some time I would really appreciate if you make a pull request.

**Comment by jdell64** [comment]
Can I create a pull request and make the edits (new to OSS).

**Comment by TWiStErRob** [comment]
@jdell64 go ahead, I didn't do it yet.

**Comment by jdell64** [comment]
Made changes, but I am unable to push... am I doing something wrong or do I not have permissions?

**Comment by TWiStErRob** [comment]
You need to fork the repo, checkout your forked repo, make changes, push, create PR pulling from forked personal repo to original repo.

**Comment by jdell64** [comment]
Thanks! I think I did it right?


--
Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

**Comment by skolmer** [comment]
@jdell64  Looks good, thanks! Can you also check the "subprocess.call('mv ' + fontfile + '.eotlite ' + fontfile + '.eot', shell=True)" in generate.py line 129
@TWiStErRob suggested this solution to make it windows compatible http://stackoverflow.com/questions/8858008/moving-a-file-in-python

**Comment by jdell64** [comment]
Sure! I'll take a look, but I did test this on a windows box.

--

Jeff Tindell

**Comment by skolmer** [comment]
Does your output dir contain an .eot file? In my case it was just throwing "'mv' is not recognized as an internal or external command" error and not renaming the .eotlite to .eot

**Comment by jdell64** [comment]
I tested on a box with some things configured... I'll test on a clean box and even edit the readme for windows instructions.

**Comment by skolmer** [comment]
Cool, thanks a lot

**Comment by jdell64** [comment]
I made the changes, and tested it on a new box. Works great. Only thing, the 'gem install' version is older than the github version, so I had to move the git hub version into the gem version to test it (on my local box). If you update the gem, windows users can also just use 'gem install fontcustom' to get it going.

**Comment by imamdev** [comment]
Hi,

I've tried to test this with:
- Windows 7 64bit
- FontCustom 1.3.8
- FontForge Release 2015-06-12

The cmd-Line told me the following:

C:\Ruby21\svgs\vincent\fonts\icons\fontcustom>fontcustom compile
C:/Ruby21/lib/ruby/2.1.0/open3.rb:193:in `spawn': No such file or directory - fo
ntforge -script C:/Ruby21/lib/ruby/gems/2.1.0/gems/fontcustom-1.3.8/lib/fontcust
om/scripts/generate.py .fontcustom-manifest.json (Errno::ENOENT)
        from C:/Ruby21/lib/ruby/2.1.0/open3.rb:193:in `popen_run'
        from C:/Ruby21/lib/ruby/2.1.0/open3.rb:93:in `popen3'
        from C:/Ruby21/lib/ruby/2.1.0/open3.rb:252:in `capture3'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/fontcustom-1.3.8/lib/fontcustom/
generator/font.rb:77:in `create_fonts'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/fontcustom-1.3.8/lib/fontcustom/
generator/font.rb:20:in `generate'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/fontcustom-1.3.8/lib/fontcustom/
base.rb:50:in `start_generators'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/fontcustom-1.3.8/lib/fontcustom/
base.rb:22:in `compile'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/fontcustom-1.3.8/lib/fontcustom/
cli.rb:77:in `compile'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:
27:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.
rb:126:in `invoke_command'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `
dispatch'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440
:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/fontcustom-1.3.8/bin/fontcustom:
5:in `<top (required)>'
        from C:/Ruby21/bin/fontcustom:23:in `load'
        from C:/Ruby21/bin/fontcustom:23:in `<main>'

Could you give me an advice what's wrong with my installation?

**Comment by jdell64** [comment]
Have you installed fontforge and added it to your path?

**Comment by imamdev** [comment]
Ahh thanks a lot, actually my FontForge path was wrong. Problem solved.

**Comment by giancarloGiuffra** [comment]
hi, I'm new to ruby but i cannot figure out what is causing the problem when trying to install the gem fontcustom. I get the following:

    C:/Ruby22-x64/bin/ruby.exe extconf.rb
    creating Makefile
    
    make "DESTDIR=" clean
    
    make "DESTDIR="
    generating hitimes-x64-mingw32.def
    /bin/sh: /C/Ruby22-x64/bin/ruby: No such file or directory
    Makefile:260: recipe for target 'hitimes-x64-mingw32.def' failed
    make: *** [hitimes-x64-mingw32.def] Error 127
    
    make failed, exit code 2

could you please help me figure it out? thanks

**Comment by jdell64** [comment]
Im not sure, but it looks like you need the dev tools.

You should consider using ruby installer or rails installer.


--
Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

**Comment by MikhailRoot** [comment]
In my case with fontcustom 1.8.3 on Windows 10 with latest FontForge for windows installed 
FontForge-2016-10-04-Windows.exe

to make fontcustom working  you need to install it as usuall 

`gem install fontcustom`

then edit base.rb :
`[ruby_dir]\lib\ruby\gems\2.3.0\gems\fontcustom-1.3.8\lib\fontcustom\base.rb`

comment out with # raising error on line 35 

`#raise Fontcustom::Error, "Please install fontforge first. Visit <http://fontcustom.com> for instructions."`

and make sure you've added FontForge directory to PATH and rebooted after adding it. 
in my case it's installed in:

`C:\Program Files (x86)\FontForgeBuilds`

to test if it's added type `which fontforge` in Command prompt if it's present it will output  PATH  env variable. ( that is why this issue exists currently on windows 10 setup).

Then try to compile your fontcustom build. you can specify debug to true as it'll help you discover further problems if encounter.

For example it's good to check permissions for TEMP directory specified in environment, if it has writing rights only for Administrator then give writing rights to your user to this directory. Without it FontForge will rise exception as it requires log files to be written in temp.

**Comment by jdell64** [comment]
Can this issue be closed? I believe it is now supported by Windows.

**Comment by julmot** [comment]
I'm currently experiencing problems

![2017-07-06 15_59_32-cmd](https://user-images.githubusercontent.com/8310677/27914639-230287ee-6264-11e7-8a9f-75ba5106ab01.png)

**Comment by jdell64** [comment]
Ah, the space... Let me see about fixing it.

**Comment by julmot** [comment]
Thanks @jdell64. I'm curious, why haven't anyone of the other Windows users mentioned this error!?

**Comment by jdell64** [comment]
Hard to say, but maybe they don't have it in "Program Files"? That might be why mine didn't fail.

**Comment by JakeBeresford** [comment]
Thanks for the continued updates here, guys. Once you can both confirm this solution is good I'll gladly merge to master and release a patch. Unfortunately I'm working remotely at the moment and don't have access to my windows machine to test. Thanks for your patience

**Comment by julmot** [comment]
@jdell64 What do you mean by "it"? I've installed FontForge according to the docs, only ruby is located inside the "Program Files" folder.

**Comment by jdell64** [comment]
Oh, weird. Do you think you could give more info surrounding this error then? What command was it that triggered this? Full stack of the error?

**Comment by julmot** [comment]
Please see my screenshot above. If you need more info, let me know the commands to run.

**Comment by jdell64** [comment]
Was this the command: 

`fontcustom compile --debug`

**Comment by julmot** [comment]
Yes, you can see this at the very top of the screenshot.

**Comment by jdell64** [comment]
(wasn't sure if that was an auto-generated command, or the one you ran)
I haven't actually used fontcustom for a little bit now (I don't make fonts often).

I actually need some help with this one. I think the issue is in `options.rb`, but I don't know enough about the project to get it just yet. The solution would be to wrap the path in quotes, but I cannot figure out which line that is.

**Comment by julmot** [comment]
@endtwist @kaizau Maybe you can help here?

**Comment by spiderjn** [comment]
Any news for windows support ?
