### ISSUE TITLE
Compilation fails with default options

### ISSUE THREAD

**Issue by jgueytat** [FontCustom/fontcustom#254]
**FontForge v. 20120731**

```
jgueytat@Mario:~/projects/jgueytat.com$ fontforge --version
Copyright (c) 2000-2012 by George Williams.
 Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
 Library based on sources from 14:57 GMT 31-Jul-2012.
fontforge 20120731
libfontforge 20120731-ML
```

**FontCustom v. 1.3.7**

```
jgueytat@Mario:~/projects/jgueytat.com$ bundle exec fontcustom --version
fontcustom-1.3.7
```

**SVG files**

```
jgueytat@Mario:~/projects/jgueytat.com$ du -h ./vectors/*
4,0K    ./vectors/facebook.svg
4,0K    ./vectors/googleplus.svg
4,0K    ./vectors/twitter.svg
```

**The command that leads to the error:**

```
jgueytat@Mario:~/projects/jgueytat.com$ bundle exec fontcustom compile --debug vectors
       debug  Generated files will be saved to `fontcustom/`.
       debug  Using options:
                {:input=>{:vectors=>"vectors", :templates=>"vectors"},
                :output=>{:fonts=>"fontcustom", :css=>"fontcustom", :preview=>"fontcustom"},
                :config=>false,
                :templates=>["css", "preview"],
                :font_name=>"fontcustom",
                :font_design_size=>16,
                :font_em=>512,
                :font_ascent=>448,
                :font_descent=>64,
                :css_selector=>".icon-{{glyph}}",
                :preprocessor_path=>nil,
                :autowidth=>false,
                :no_hash=>false,
                :debug=>true,
                :force=>false,
                :quiet=>false}
      delete  fontcustom/fontcustom_8882ee0e631955d24f0ac92a4feb374b.ttf
              fontcustom/fontcustom_8882ee0e631955d24f0ac92a4feb374b.svg
       debug  Copyright (c) 2000-2012 by George Williams.
               Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
               Library based on sources from 14:57 GMT 31-Jul-2012.
              Traceback (most recent call last):
                File "/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/fontcustom-1.3.7/lib/fontcustom/scripts/generate.py", line 116, in <module>
                  subprocess.call(['sfnt2woff', fontfile + '.ttf'])
                File "/usr/lib/python2.7/subprocess.py", line 522, in call
                  return Popen(*popenargs, **kwargs).wait()
                File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
                  errread, errwrite)
                File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
                  raise child_exception
              OSError: [Errno 2] Aucun fichier ou dossier de ce type
       error  `fontforge` compilation failed.
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/fontcustom-1.3.7/lib/fontcustom/generator/font.rb:92:in `create_fonts'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/fontcustom-1.3.7/lib/fontcustom/generator/font.rb:20:in `generate'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/fontcustom-1.3.7/lib/fontcustom/base.rb:50:in `start_generators'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/fontcustom-1.3.7/lib/fontcustom/base.rb:22:in `compile'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/fontcustom-1.3.7/lib/fontcustom/cli.rb:77:in `compile'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/gems/fontcustom-1.3.7/bin/fontcustom:5:in `<top (required)>'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/bin/fontcustom:23:in `load'
/home/jgueytat/projects/jgueytat.com/vendor/bundle/ruby/2.1.0/bin/fontcustom:23:in `<main>'
```

Any help appreciated! :)

**Comment by kaizau** [comment]
"Aucun fichier ou dossier de ce type" Google translates to "No files or folders of this type". So I'm a bit stumped as well. Will flag this for investigation.
