### ISSUE TITLE
Error in `fontforge': double free or corruption (out): 0x0000000000d51910

### ISSUE THREAD

**Issue by reinierbutot** [FontCustom/fontcustom#331]
I am trying to compile icons. Using a docker image based on this:
```
buildpack-deps:jessie
```

And this is the installation procedure i followed:
(note the omission of sudo, because these commands are executed inside docker)
```
apt-get install fontforge
wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && mv sfnt2woff /usr/local/bin/
gem install fontcustom
```

This finishes successfully, but the error appears when I try to compile:

```
fontcustom compile --debug
```

The error:

```
       debug  Using settings from `fontcustom.yml`.
       debug  Using options:
                {:input=>
                 {:vectors=>"support/icons/vectors", :templates=>"support/icons/templates"},
                :output=>
                 {:fonts=>"app/assets/fonts",
                  :"_font_icons.sass"=>"app/assets/stylesheets/application/utilities/icons",
                  :"_icon_font.sass"=>"app/assets/stylesheets/application/utilities/icons",
                  :css=>"app/assets/fonts",
                  :preview=>"app/assets/fonts"},
                :config=>"fontcustom.yml",
                :templates=>["_font_icons.sass", "_icon_font.sass"],
                :font_name=>"icons",
                :font_design_size=>16,
                :font_em=>512,
                :font_ascent=>448,
                :font_descent=>64,
                :css_selector=>".icon-{{glyph}}",
                :preprocessor_path=>nil,
                :autowidth=>false,
                :no_hash=>true,
                :debug=>true,
                :force=>false,
                :quiet=>false}
*** Error in `fontforge': double free or corruption (out): 0x0000000000d51910 ***
       debug  Copyright (c) 2000-2012 by George Williams.
               Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
               Library based on sources from 14:57 GMT 31-Jul-2012.
       error  `fontforge` compilation failed.
/usr/local/bundle/gems/fontcustom-1.3.8/lib/fontcustom/generator/font.rb:92:in `create_fonts'
/usr/local/bundle/gems/fontcustom-1.3.8/lib/fontcustom/generator/font.rb:20:in `generate'
/usr/local/bundle/gems/fontcustom-1.3.8/lib/fontcustom/base.rb:50:in `start_generators'
/usr/local/bundle/gems/fontcustom-1.3.8/lib/fontcustom/base.rb:22:in `compile'
/usr/local/bundle/gems/fontcustom-1.3.8/lib/fontcustom/cli.rb:77:in `compile'
/usr/local/bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/usr/local/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/usr/local/bundle/gems/fontcustom-1.3.8/bin/fontcustom:5:in `<top (required)>'
/usr/local/bundle/bin/fontcustom:22:in `load'
```

**Comment by CanbingChen** [comment]
I also get this problem.

**Comment by CanbingChen** [comment]
I solved my problem.I only install zlib.h
