### ISSUE TITLE
`fontforge` compilation failed - segfault

### ISSUE THREAD

**Issue by Averethel** [FontCustom/fontcustom#355]
I installed the newest version of fontforge (via homebrew) and since then it does not work.

Debug output:
```
       debug  Using settings from `fontcustom.yml`.
       debug  Using options:
                {:input=>{:vectors=>"glyphs", :templates=>"templates"},
                :output=>
                 {:fonts=>"../assets/fonts/local-ui",
                  :css=>"../assets/stylesheets/local-ui",
                  :"iconfont.yml"=>"../documentation/data",
                  :preview=>"../assets/fonts/local-ui"},
                :config=>"fontcustom.yml",
                :templates=>["iconfont.yml", "_iconfont.scss"],
                :font_name=>"iconfont",
                :font_design_size=>16,
                :font_em=>512,
                :font_ascent=>448,
                :font_descent=>64,
                :css_selector=>".icon-{{glyph}}",
                :preprocessor_path=>nil,
                :autowidth=>false,
                :no_hash=>true,
                :css3=>false,
                :debug=>true,
                :force=>false,
                :quiet=>false,
                :copyright=>""}
       debug  Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
               License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
               with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
               Based on sources from 21:22 UTC  6-Aug-2017-D.
               Based on source from git with hash:
       error  `fontforge` compilation failed.
/Users/neithan/.gem/ruby/2.3.3/gems/fontcustom-2.0.0/lib/fontcustom/generator/font.rb:92:in `create_fonts'
/Users/neithan/.gem/ruby/2.3.3/gems/fontcustom-2.0.0/lib/fontcustom/generator/font.rb:20:in `generate'
/Users/neithan/.gem/ruby/2.3.3/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:62:in `start_generators'
/Users/neithan/.gem/ruby/2.3.3/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:23:in `compile'
/Users/neithan/.gem/ruby/2.3.3/gems/fontcustom-2.0.0/lib/fontcustom/cli.rb:83:in `compile'
/Users/neithan/.gem/ruby/2.3.3/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/neithan/.gem/ruby/2.3.3/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/neithan/.gem/ruby/2.3.3/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/neithan/.gem/ruby/2.3.3/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Users/neithan/.gem/ruby/2.3.3/gems/fontcustom-2.0.0/bin/fontcustom:5:in `<top (required)>'
/Users/neithan/.gem/ruby/2.3.3/bin/fontcustom:23:in `load'
/Users/neithan/.gem/ruby/2.3.3/bin/fontcustom:23:in `<main>'
```

After that, I tried to manually execute fontforge with the same arguments as the gem does it. The result is:
```
fontforge --script ~/.gem/ruby/2.3.3/gems/fontcustom-2.0.0/lib/fontcustom/scripts/generate.py .fontcustom-manifest.json
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 21:22 UTC  6-Aug-2017-D.
 Based on source from git with hash:
[1]    17190 segmentation fault  fontforge --script  .fontcustom-manifest.json
```

Fonforge version:
```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 21:22 UTC  6-Aug-2017-D.
 Based on source from git with hash:
fontforge 21:22 UTC  6-Aug-2017
libfontforge 20170806
```

I checked if this could be related to broken python libraries but it seems that they can be loaded.
```
python -c "import fontforge"
```
works as expected

**Comment by prakvem** [comment]
+1 
Have the same issue 
Mac El Capitan 10.11.6
Fontforge 20170731
Fontcustom 2.0.0
Ruby 2.3.0
Woff2
