### ISSUE TITLE
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 113: ordinal not in range

### ISSUE THREAD

**Issue by zhangsanshi** [FontCustom/fontcustom#361]
when run command get error
```
fontcustom compile /path/to/svg/font --no_hash true --force true --font_name i-font --css-selector .i-font-{{glyph}} --preprocessor_path /res/fonts --templates preview ../../../../gulp/fontcustom.css --output ./
```

```
       debug  Using options:
                {:input=>
                 {:vectors=>
                   "/path/to/svg/font",
                  :templates=>
                   "/path/to/svg/font"},
                :output=>{:fonts=>"./", :css=>"./", :preview=>"./"},
                :config=>false,
                :templates=>["preview", "../../../../gulp/fontcustom.css"],
                :font_name=>"i-font",
                :font_design_size=>16,
                :font_em=>512,
                :font_ascent=>448,
                :font_descent=>64,
                :css_selector=>".i-font-{{glyph}}",
                :preprocessor_path=>"/res/fonts",
                :autowidth=>false,
                :no_hash=>true,
                :css3=>false,
                :debug=>true,
                :force=>true,
                :quiet=>false,
                :copyright=>""}
      status  Forcing compile.
        warn  `/path/to/svg/font/next.svg` contains transparency and will be skipped.
       debug  Copyright (c) 2000-2012 by George Williams.
               Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
               Library based on sources from 14:57 GMT 31-Jul-2012.
              Traceback (most recent call last):
                File "/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/lib/fontcustom/scripts/generate.py", line 88, in <module>
                  name = createGlyph(glyph, data['source'], data['codepoint'])
                File "/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/lib/fontcustom/scripts/generate.py", line 66, in createGlyph
                  temp = removeSwitchFromSvg(source)
                File "/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/lib/fontcustom/scripts/generate.py", line 57, in removeSwitchFromSvg
                  tmpsvgfile.file.write(svgtext.encode('utf-8'))
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 113: ordinal not in range(128)
       error  `fontforge` compilation failed.
/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/lib/fontcustom/generator/font.rb:92:in `create_fonts'
/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/lib/fontcustom/generator/font.rb:20:in `generate'
/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:62:in `start_generators'
/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:23:in `compile'
/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/lib/fontcustom/cli.rb:83:in `compile'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.3.0/gems/fontcustom-2.0.0/bin/fontcustom:5:in `<top (required)>'
/usr/local/bin/fontcustom:23:in `load'
/usr/local/bin/fontcustom:23:in `<main>'
```
env:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
gems: 2.3.0
fontcustom: 2.0.0
```

**Comment by MonwF** [comment]
see solution  https://github.com/FontCustom/fontcustom/issues/347#issuecomment-323578812
