### ISSUE TITLE
`fontforge` compilation failed. 'float' object cannot be interpreted as an integer.

### ISSUE THREAD

**Issue by dapaopaopao** [FontCustom/fontcustom#395]
```
 debug  Using options:
                {:input=>
                 {:vectors=>"/Users/xumingze/youdata/Platform/src/app/client/res/svg",
                  :templates=>"/Users/xumingze/youdata/Platform/src/app/client/res/svg"},
                :output=>{:fonts=>"./", :css=>"./", :preview=>"./"},
                :config=>false,
                :templates=>["preview", "../fontcustom.css"],
                :font_name=>"youdata",
                :font_design_size=>16,
                :font_em=>512,
                :font_ascent=>448,
                :font_descent=>64,
                :css_selector=>".u-icn-{{glyph}}",
                :preprocessor_path=>"/fonts",
                :autowidth=>false,
                :no_hash=>true,
                :css3=>false,
                :debug=>true,
                :force=>true,
                :quiet=>false,
                :copyright=>""}
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
      status  Forcing compile.
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
       debug  Copyright (c) 2000-2023. See AUTHORS for Contributors.
               License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
               with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
               Version: 20230101
               Based on sources from 2023-01-01 05:27 UTC-D.
              Traceback (most recent call last):
                File "/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fontcustom-2.0.0/lib/fontcustom/scripts/generate.py", line 89, in <module>
                  name = createGlyph(glyph, data['source'], data['codepoint'])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fontcustom-2.0.0/lib/fontcustom/scripts/generate.py", line 81, in createGlyph
                  glyph.left_side_bearing = glyph.left_side_bearing - shift
                  ^^^^^^^^^^^^^^^^^^^^^^^
              TypeError: 'float' object cannot be interpreted as an integer
       error  `fontforge` compilation failed.
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fontcustom-2.0.0/lib/fontcustom/generator/font.rb:92:in `create_fonts'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fontcustom-2.0.0/lib/fontcustom/generator/font.rb:20:in `generate'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:62:in `start_generators'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:23:in `compile'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fontcustom-2.0.0/lib/fontcustom/cli.rb:83:in `compile'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fontcustom-2.0.0/bin/fontcustom:5:in `<top (required)>'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/bin/fontcustom:23:in `load'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/bin/fontcustom:23:in `<main>'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/Users/xumingze/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
xumingze@HIH-L-12191 ~ % 
```

**Comment by rlmoser99** [comment]
I had this error today following the instructions in the README. I fixed my issue by installing an older version of `fontforge`.

https://fontforge.org/en-US/downloads/mac-dl/
Click on the button "For releases before 2019-03-17" and follow the directions to install XQuartz and FontForge. I also had an issue opening FontForge because it was downloaded from the internet, but I was able to open it by right-clicking and choosing "Open".

**Comment by dapaopaopao** [comment]
thx
fix it by installing the 2020-03-14 version of fontforge

**Comment by kontur** [comment]
How did manually installing that version install the CLI required for fontcustom? For me this process failed.

**Comment by rlmoser99** [comment]
Installing the older versions of XQuartz and FontForge using the link above installed a GUI. In order for others to help you, you should provide more details on when this process failed for you, what error messages you are seeing, and maybe even what OS you are using.

**Comment by kontur** [comment]
I am seeing the exact same error message `TypeError: 'float' object cannot be interpreted as an integer`. I guess my question is exactly as you state, I manage to follow installing the "For releases before 2019-03-17" as advised above, but I fail to see how this will fix the fontcustom error. For me, the custom GUI install has not had any effect on fontcustom, so I am wonder how this fixed it for you and dapaopaopao.

**Comment by rlmoser99** [comment]
Another thing that I did during my troubleshooting was editing the path by adding the following line to my `.zshrc` file, then closing and reopening terminal.

  ```sh
  export PATH="/Applications/FontForge.app/Contents/Resources/opt/local/bin:$PATH"
  ```
