### ISSUE TITLE
/usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/lib/fontcustom/options.rb:50:in `set_config_path': undefined method `exists?' for File:Class (NoMethodError)          if File.exists? "fontcustom.yml"       

### ISSUE THREAD

**Issue by Wowoy** [FontCustom/fontcustom#399]
fontcustom compile /Users/xxx/... --no_hash true --force true ...
[21:44:49] Plumber found unhandled error:
 Error in plugin 'gulp_fontcustom'
Message:
    Command failed: fontcustom compile /Users/xxx/... --no_hash true --force true ...
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/lib/fontcustom/options.rb:50:in `set_config_path': undefined method `exists?' for File:Class (NoMethodError)

        if File.exists? "fontcustom.yml"
               ^^^^^^^^
Did you mean?  exist?
        from /usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/lib/fontcustom/options.rb:18:in `parse_options'
        from /usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/lib/fontcustom/options.rb:11:in `initialize'
        from /usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:12:in `new'
        from /usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:12:in `initialize'
        from /usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/lib/fontcustom/cli.rb:83:in `new'
        from /usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/lib/fontcustom/cli.rb:83:in `compile'
        from /usr/local/lib/ruby/gems/3.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /usr/local/lib/ruby/gems/3.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/fontcustom-2.0.0/bin/fontcustom:5:in `<top (required)>'
        from /usr/local/bin/fontcustom:25:in `load'
        from /usr/local/bin/fontcustom:25:in `<main>'

Details:
    killed: false
    code: 1
    signal: null
    cmd: fontcustom compile /Users/xxx/... --no_hash true --force true ...
[21:44:49] Plumber found unhandled error:
 Error: write callback called multiple times
[21:44:49] Finished 'iconfont' after 693 ms

**Comment by TWiStErRob** [comment]
Downgrade to Ruby 2.7.8, see https://www.reddit.com/r/ruby/comments/1196wti/psa_and_a_little_rant_fileexists_direxists/, even if you go to 3.1.4, you'll be hit by #390
